syntax = "proto3";

package forge.v1;

option java_package = "dev.forge.proto";
option java_multiple_files = true;

service ForgeController {

  rpc RegisterWorker(RegisterWorkerRequest)
      returns (RegisterWorkerResponse);

  rpc Heartbeat(HeartbeatRequest)
      returns (HeartbeatResponse);
  
  rpc ConnectWorker(stream WorkerMessage)
    returns (stream ControllerMessage);
}

message WorkerMessage {
  oneof payload {
    WorkerHello hello = 1;
    WorkerHeartbeat heartbeat = 2;
    TaskAccepted task_accepted = 3;
    TaskResult task_result = 4;
  }
}

message ControllerMessage {
  oneof payload {
    TaskAssignment task_assignment = 1;
  }
}

message WorkerHello {
  string worker_id = 1;
  string hostname = 2;
  uint32 cpu_cores = 3;
  uint64 memory_bytes = 4;
  string operating_system = 5;
}

message WorkerHeartbeat {
  string worker_id = 1;
  double cpu_usage_percent = 2;
  uint64 memory_used_bytes = 3;
  uint32 running_tasks = 4;
}

message TaskAssignment {
  string task_id = 1;
  string command = 2;
  repeated string arguments = 3;
  string attempt_id = 4;
}

message TaskAccepted {
  string task_id = 1;
  string attempt_id = 2;
}

message TaskResult {
  string task_id = 1;

  int32 exit_code = 2;

  string stdout = 3;
  string stderr = 4;

  bool success = 5;

  string attempt_id = 6;
}

message RegisterWorkerRequest {
  string worker_id = 1;
  string hostname = 2;
  uint32 cpu_cores = 3;
  uint64 memory_bytes = 4;
  string operating_system = 5;
}

message RegisterWorkerResponse {
  bool accepted = 1;
  string message = 2;
}

message HeartbeatRequest {
  string worker_id = 1;

  double cpu_usage_percent = 2;

  uint64 memory_used_bytes = 3;

  uint32 running_tasks = 4;
}

message HeartbeatResponse {
  bool accepted = 1;
}

