plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.google.protobuf' version '0.10.0'
}

group = 'dev.forge'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

def grpcVersion = '1.83.1'
def protobufVersion = '3.25.8'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation enforcedPlatform("io.grpc:grpc-bom:${grpcVersion}")

    implementation 'io.grpc:grpc-protobuf'
    implementation 'io.grpc:grpc-stub'
    runtimeOnly 'io.grpc:grpc-netty-shaded'

    compileOnly 'org.apache.tomcat:annotations-api:6.0.53'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${protobufVersion}"
    }

    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
    }

    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}

sourceSets {
    main {
        proto {
            srcDir '../proto'
        }
    }
}
tasks.named('test') {
	useJUnitPlatform()
}
