package dev.forge.controller.event;


public enum ExecutionEventType {

    TASK_CREATED,
    TASK_BLOCKED,
    TASK_PENDING,
    TASK_DISPATCHED,
    TASK_RUNNING,
    TASK_SUCCEEDED,
    TASK_FAILED,
    TASK_LOST,
    TASK_CANCELLED,
    TASK_SKIPPED,

    ATTEMPT_CREATED,
    ATTEMPT_DISPATCHED,
    ATTEMPT_RUNNING,
    ATTEMPT_SUCCEEDED,
    ATTEMPT_FAILED,
    ATTEMPT_LOST,
    ATTEMPT_CANCELLED,

    RETRY_SCHEDULED,

    WORKER_LOST,

    WORKFLOW_CREATED,
    WORKFLOW_CANCEL_REQUESTED,
    WORKFLOW_RETRY_REQUESTED
}
